### ISSUE TITLE
CpeException not found

### ISSUE THREAD

**Issue by sunxinyu6122** [sportarchive/CloudProcessingEngine#10]
Fatal error: Class 'SA\CpeSdk\Swf\CpeSdk\CpeException' not found in /home/ec2-user/CloudTransCode/CloudProcessingEngine/pollers/vendor/sportarchive/cloud-processing-engine-sdk/src/SA/CpeSdk/Swf/CpeSwfHandler.php on line 19
^C
[1]+  Exit 255                php ActivityPoller.php -d -D MyDomain -T ValidateInputAndAsset-v2 -A ValidateInputAndAsset -V v2

**Comment by koxon** [comment]
The use SA\CpeSdk is missing.
I'll fix it...

On Sun, Jul 19, 2015 at 3:41 AM, sunxinyu6122 notifications@github.com
wrote:

> Fatal error: Class 'SA\CpeSdk\Swf\CpeSdk\CpeException' not found in
> /home/ec2-user/CloudTransCode/CloudProcessingEngine/pollers/vendor/sportarchive/cloud-processing-engine-sdk/src/SA/CpeSdk/Swf/CpeSwfHandler.php
> on line 19
> ^C
> [1]+ Exit 255 php ActivityPoller.php -d -D MyDomain -T
> ValidateInputAndAsset-v2 -A ValidateInputAndAsset -V v2
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sportarchive/CloudProcessingEngine/issues/10.

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.

**Comment by koxon** [comment]
done

**Comment by sunxinyu6122** [comment]
Thank you for your reply. However, I still have this question when I start the activitypoller by "php ActivityPoller.php -d -D MyDomain -T ValidateInputAndAsset-v2 -A ValidateInputAndAsset -V v2 &". I have already update the /CloudProcessingEngine/pollers/src/ActivityPoller.php, what should I do after that?

**Comment by sportarc** [comment]
The documentation should be enough to understand the concept ans structure
of the project.
What is it you don't understand?

On Sun, Jul 19, 2015 at 10:12 PM, sunxinyu6122 notifications@github.com
wrote:

> Thank you for your reply. However, I still have this question when I start
> the activitypoller by "php ActivityPoller.php -d -D MyDomain -T
> ValidateInputAndAsset-v2 -A ValidateInputAndAsset -V v2 &". I have already
> update the /CloudProcessingEngine/pollers/src/ActivityPoller.php, what
> should I do after that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sportarchive/CloudProcessingEngine/issues/10#issuecomment-122730650
> .

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.
